version: '2'
services:
  db:
    image: postgres
  manifesto:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/responsible-coders-manifesto
    ports:
      - "3000:3000"
    depends_on:
      - db
