version: '2'
services:
  db:
    image: postgres
  manifesto:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - manifesto-sync:/app:rw
      - bundle-sync:/bundle:rw
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  manifesto-sync:
    external: true
  bundle-sync:
    external: true
