development:
  pool: 5
  timeout: 5000
  database: db/development.sqlite3

test:
  pool: 5
  timeout: 5000
  database: db/test.sqlite3

production:
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  pool: 5
  database: <%= ENV.fetch('POSTGRES_DB', '') %>
  username: <%= ENV.fetch('POSTGRES_USER', '') %>
  password: <%= ENV.fetch('POSTGRES_PASS', '') %>
