development:
  pool: 5
  timeout: 5000
  database: db/development.sqlite3

test:
  pool: 5
  timeout: 5000
  database: db/test.sqlite3

production:
  adapter: postgresql
  host: localhost
  port: 5432
  pool: 5
  database: <%= Rails.application.secrets[:database][:name] %>
  username: <%= Rails.application.secrets[:database][:username] %>
  password: <%= Rails.application.secrets[:database][:password] %>
